import { StyleSheet, Platform, StatusBar } from 'react-native';

const colors = {
  primary: '#05F2AF', // destaque principal
  secondary: '#0597F2', // 2º tom para botões e ênfase
  accent1: '#04C4D9', // labels, bordas e tags
  accent2: '#04D9C4', // botões secundários e destaques
  accent3: '#05F2AF',
  accent4: '#04C4D9',
  white: '#fff',
  lightGray: 'rgba(255,255,255,0.12)',
  background: '#051F40',
  card: '#072A5A',
  textPrimary: '#E8F8FF',
  textSecondary: '#BBDFFF',
  danger: '#FF6B6B',
  success: '#05F2AF',
  warning: '#F2D904',
  info: '#0597F2',
  disabled: '#5B7A9B',
};

export const themeColors = colors;

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 20 : 20,
    backgroundColor: colors.background,
  },
  pageContent: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 10 : 10,
    paddingBottom: 30,
    backgroundColor: colors.background,
  },
  centeredContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  loginContent: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 80,
  },
  flexOne: {
    flex: 1,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    borderLeftWidth: 4,
    borderLeftColor: colors.accent1,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
    width: '100%',
  },
  cardHeaderInfo: {
    flex: 1,
    alignItems: 'center',
  },
  cardHeaderRight: {
    alignItems: 'flex-end',
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 4,
    textAlign: 'center',
  },
  cardSubtitle: {
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  cardSection: {
    marginBottom: 16,
    width: '100%',
    alignItems: 'center',
  },
  cardSectionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
    marginBottom: 8,
    textAlign: 'center',
  },
  cardText: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
    textAlign: 'center',
  },
  cardButton: {
    borderRadius: 12,
    paddingVertical: 12,
  },
  denunciaCard: {
    maxWidth: '100%',
    alignSelf: 'auto',
  },
  denunciaCardHeaderInfo: {
    alignItems: 'stretch',
  },
  denunciaCardTitle: {
    textAlign: 'left',
  },
  denunciaCardSubtitle: {
    textAlign: 'left',
  },
  denunciaCardSection: {
    alignItems: 'stretch',
  },
  denunciaCardText: {
    textAlign: 'left',
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  badgeText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 12,
  },
  statusChip: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 20,
    marginBottom: 8,
  },
  statusChipText: {
    fontWeight: 'bold',
    fontSize: 12,
  },
  rowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
  },
  emptyStateTitle: {
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: '600',
    marginTop: 16,
    textAlign: 'center',
  },
  emptyStateText: {
    color: colors.textSecondary,
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
    lineHeight: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
  },
  modalSection: {
    backgroundColor: colors.card,
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    alignItems: 'center',
  },
  modalSectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
    marginBottom: 8,
  },
  denunciaModalSection: {
    maxWidth: '100%',
    alignItems: 'stretch',
  },
  denunciaLabel: {
    alignSelf: 'auto',
    textAlign: 'left',
  },
  denunciaFlatlistContentContainer: {
    paddingBottom: 30,
  },
  modalText: {
    color: colors.textSecondary,
    lineHeight: 20,
  },
  messageBubble: {
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
    maxWidth: '85%',
  },
  messageBubbleMeta: {
    fontSize: 10,
    marginTop: 6,
    color: colors.textSecondary,
  },
  infoBox: {
    marginTop: 30,
    padding: 15,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 12,
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    alignItems: 'center',
  },
  infoBoxTitle: {
    fontWeight: 'bold',
    marginBottom: 8,
    color: colors.primary,
  },
  infoBoxText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  textHelper: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 4,
  },
  textArea: {
    textAlignVertical: 'top',
    paddingTop: 12,
    height: 140,
    maxHeight: 140,
  },
  pickerContainer: {
    backgroundColor: colors.card,
    borderRadius: 10,
    marginBottom: 20,
    justifyContent: 'center',
    paddingHorizontal: 0,
    paddingVertical: 0,
    width: '85%',
    maxWidth: 420,
    alignSelf: 'center',
    overflow: 'hidden',
  },
  whitePickerContainer: {
    backgroundColor: colors.white,
    borderRadius: 10,
    marginBottom: 20,
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 0,
  },
  pickerStyle: {
    color: colors.textPrimary,
    height: 50,
    width: '100%',
  },
  containerHome: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    paddingTop: 50,
    backgroundColor: colors.background,
  },
  titulo: {
    fontSize: 22, //titulo principais
    fontWeight: 'bold',
    color: colors.primary,
    marginTop: 10,
    marginBottom: 10,
    textAlign: 'center',
    alignSelf: 'center',
  },
  logo: {
    width: 250,
    height: 270,
  
  },
  label: {
    color: colors.accent1,
    fontWeight: 'bold',
    marginTop: 10, //distancia de itens
    textAlign: 'center',
    alignSelf: 'center',
  },
  text: {
    fontSize: 16,
    color: colors.textPrimary,
    marginBottom: 10,
    textAlign: 'center',
  },
  inputView: {
    width: '85%',
    maxWidth: 420,
    alignSelf: 'center',
    marginBottom: 20,
  },
  input: {
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
    marginBottom: 20,
    backgroundColor: colors.white,
    color: colors.background,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  inputPicker: {
    marginBottom: 20,
    backgroundColor: colors.card,
    paddingLeft: 8,
  },
  textPicker: {
    fontSize: 16,
  },
  buttonView: {
    width: '85%',
    maxWidth: 420,
    alignSelf: 'center',
    alignItems: 'center',
  },
  button: {
    backgroundColor: colors.accent2,
    width: '100%',
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 50,
  },
  buttonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
  },
  buttonSecondary: {
    backgroundColor: colors.card,
    borderColor: colors.accent1,
    borderWidth: 2,
  },
  buttonSecondaryText: {
    color: colors.accent1,
    fontWeight: 'bold',
    fontSize: 16,
  },
  buttonOutline: {
    backgroundColor: 'transparent',
    borderColor: colors.accent1,
    borderWidth: 2,
  },
  buttonOutlineText: {
    color: colors.accent1,
  },
  buttonFlex: {
    flex: 1,
  },
  // Botões padronizados do app
  botao: {
    backgroundColor: colors.accent2,
    width: '85%',
    maxWidth: 420,
    alignSelf: 'center',
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 50,
  },
  textoBotao: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
  },
  // filtros de admin
  filterContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginBottom: 15,
    gap: 8,
  },
  filterButton: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 999,
    borderWidth: 1,
  },
  filterButtonActive: {
    backgroundColor: colors.accent2,
    borderColor: colors.accent2,
  },
  filterButtonInactive: {
    backgroundColor: colors.card,
    borderColor: colors.accent1,
  },
  filterButtonTextActive: {
    color: colors.white,
    fontWeight: 'bold',
  },
  filterButtonTextInactive: {
    color: colors.accent1,
    fontWeight: 'bold',
  },
  //cancelar reserva
  buttonDelete: {
    backgroundColor: colors.danger,
    flex: 1,
  },
  //style "minhas reservas"
  listItem: {
    backgroundColor: colors.lightGray,
    borderBottomWidth: 1,
    borderBottomColor: colors.accent3,
    padding: 10,
    marginTop: 10,
    width: '90%',
    borderRadius: 10,
    alignSelf: 'center',
  },
  lightCard: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: 'rgba(5, 242, 175, 0.25)',
    padding: 12,
    marginTop: 10,
    width: '90%',
    borderRadius: 12,
    alignSelf: 'center',
  },
  listText: {
    fontSize: 17,
  },
  labelFormTitle: {
    color: colors.accent2,
    fontWeight: 'bold',
    marginTop: 10,
  },
  backButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 10,
    paddingTop: 10,
  },
  backButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.accent1,
    padding: 10,
    borderRadius: 10,
  },
  backButtonText: {
    color: colors.white,
    marginLeft: 14,
    fontWeight: 'bold',
  },
  actionButtonsRow: {
    flexDirection: 'row',
    marginTop: 10,
    gap: 10,
  },
  //style "perfil"
  profileFormContainer: {
    width: '90%',
    maxWidth: 520,
    alignSelf: 'center',
    marginTop: 20,
  },
  profileContainer: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 55,
    paddingHorizontal: 20,
    backgroundColor: colors.background,
  },

  avatarContainer: {
    alignItems: 'center',
    marginBottom: 24,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.accent2,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  avatarText: {
    color: colors.white,
    fontSize: 36,
    fontWeight: 'bold',
  },
  profileName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.primary,
  },
  optionsContainer: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    marginTop: 10,
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderRadius: 14,
    backgroundColor: colors.card,
    marginBottom: 12,
  },
  optionIcon: {
    fontSize: 22,
    marginRight: 14,
  },
  optionText: {
    fontSize: 16,
    color: colors.textPrimary,
    fontWeight: '600',
  },
  logoutButton: {
    backgroundColor: colors.danger,
    width: '100%',
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  activeText: {
    color: colors.accent2,
    fontWeight: '700',
  },
  expiredText: {
    color: colors.danger,
    fontWeight: '700',
  },
  tabsContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 12,
    padding: 4,
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  activeTab: {
    backgroundColor: colors.card,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  tabText: {
    fontSize: 16,
    color: colors.primary,
    fontWeight: '500',
  },
  activeTabText: {
    color: colors.accent2,
    fontWeight: '700',
  },
  flatlistContentContainer: {
    alignItems: 'center',
    width: '100%',
    paddingBottom: 30,
  },
  dashboard: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignSelf: 'center',
    width: '100%',
    maxWidth: 520,
    marginBottom: 20,
    flexWrap: 'wrap',
  },
  metricCard: {
    backgroundColor: colors.card,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    width: '30%',
    minWidth: 100,
    marginBottom: 10,
  },
  metricTitle: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  metricValue: {
    fontSize: 24,
    color: colors.accent2,
    fontWeight: 'bold',
    marginTop: 5,
  },
  chartContainer: {
    width: '90%',
    backgroundColor: colors.card,
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
  },
  chartTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 12,
  },
  chartBars: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    width: '100%',
  },
  chartColumn: {
    alignItems: 'center',
    width: '30%',
  },
  chartBar: {
    width: '100%',
    maxWidth: 80,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 12,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    minHeight: 20,
  },
  chartBarFill: {
    width: '100%',
    borderRadius: 12,
    flex: 1,
  },
  chartValueLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
    marginTop: 8,
  },
  chartBarLabel: {
    fontSize: 12,
    color: colors.accent1,
    marginTop: 2,
  },
  adminScreen: {
    flex: 1,
    width: '100%',
    backgroundColor: colors.background,
  },
  adminContent: {
    paddingHorizontal: 18,
    paddingTop: 54,
    paddingBottom: 34,
  },
  adminTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.primary,
    textAlign: 'center',
    marginBottom: 6,
  },
  adminSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: 22,
  },
  adminMetricsGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 14,
  },
  adminMetricCard: {
    flex: 1,
    minHeight: 150,
    backgroundColor: colors.card,
    borderRadius: 18,
    padding: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 6,
  },
  adminMetricIcon: {
    width: 58,
    height: 58,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  adminMetricLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    minHeight: 32,
  },
  adminMetricValue: {
    color: colors.primary,
    fontSize: 30,
    fontWeight: '900',
    marginTop: 4,
  },
  adminStatsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  adminStatCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(5,242,175,0.12)',
  },
  adminWideStatCard: {
    backgroundColor: 'rgba(4,196,217,0.12)',
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(4,196,217,0.22)',
  },
  adminStatLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 7,
  },
  adminStatValue: {
    color: colors.primary,
    fontSize: 24,
    fontWeight: '900',
  },
  adminWideStatValue: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: '800',
  },
  adminPanel: {
    backgroundColor: colors.card,
    borderRadius: 18,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
    elevation: 5,
  },
  adminSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
    gap: 12,
  },
  adminSectionTitle: {
    color: colors.primary,
    fontSize: 17,
    fontWeight: '900',
  },
  adminSectionMeta: {
    color: colors.accent1,
    fontSize: 13,
    fontWeight: '800',
  },
  adminChart: {
    height: 190,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 10,
  },
  adminChartColumn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  adminChartTrack: {
    height: 132,
    width: '100%',
    maxWidth: 54,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 16,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  adminChartFill: {
    width: '100%',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  adminChartValue: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 8,
  },
  adminChartLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 8,
    textAlign: 'center',
  },
  adminQuickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  adminQuickAction: {
    width: '47%',
    minHeight: 102,
    backgroundColor: 'rgba(255,255,255,0.09)',
    borderRadius: 16,
    padding: 14,
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  adminQuickIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  adminQuickText: {
    color: colors.textPrimary,
    fontWeight: '800',
    fontSize: 14,
  },
  adminPendingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(242,217,4,0.1)',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(242,217,4,0.22)',
  },
  adminPendingInfo: {
    flex: 1,
  },
  adminPendingTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 4,
  },
  adminPendingText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  adminActivityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  adminActivityIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adminActivityTextWrap: {
    flex: 1,
  },
  adminActivityTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 3,
  },
  adminActivityText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  adminEmptyText: {
    color: colors.textSecondary,
    textAlign: 'center',
    paddingVertical: 12,
  },
  reservaScrollContent: {
    width: '100%',
    paddingHorizontal: 18,
    paddingTop: 56,
    paddingBottom: 32,
  },
  reservaScreen: {
    flex: 1,
    width: '100%',
    backgroundColor: colors.background,
  },
  reservaList: {
    flex: 1,
    width: '100%',
  },
  reservaHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  reservaIconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reservaHeaderTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.primary,
  },
  reservaSearchWrapper: {
    position: 'relative',
    marginBottom: 16,
  },
  reservaSearchIcon: {
    position: 'absolute',
    left: 14,
    top: 20,
    zIndex: 1,
  },
  reservaSearchInput: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    paddingLeft: 26,
    borderRadius: 14,
  },
  reservaFilterRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  reservaFilterChip: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 999,
    alignItems: 'center',
    borderWidth: 1,
  },
  reservaFilterChipActive: {
    backgroundColor: colors.accent2,
    borderColor: colors.accent2,
  },
  reservaFilterChipInactive: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderColor: colors.accent1,
  },
  reservaFilterChipTextActive: {
    color: colors.white,
    fontWeight: '700',
  },
  reservaFilterChipTextInactive: {
    color: colors.accent1,
    fontWeight: '700',
  },
  reservaRefreshButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 18,
    gap: 8,
  },
  reservaRefreshButtonText: {
    color: colors.primary,
    fontWeight: '700',
  },
  reservaListContent: {
    paddingBottom: 24,
  },
  reservaListSeparator: {
    height: 14,
  },
  reservaCardsContainer: {
    gap: 14,
  },
  reservaStreetCard: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(5,151,242,0.18)',
  },
  reservaStreetCardPressed: {
    transform: [{ scale: 0.985 }],
    opacity: 0.92,
  },
  reservaStreetCardSelected: {
    borderColor: colors.accent3,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  
  },
  reservaStreetTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 8,
  },
  reservaStreetTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.primary,
  },
  reservaStreetMeta: {
    color: colors.textSecondary,
    marginTop: 4,
    fontSize: 13,
  },
  reservaStreetCount: {
    fontSize: 16,
    color: colors.accent2,
    fontWeight: '700',
    marginBottom: 14,
  },
  reservaBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  reservaBadgeAvailable: {
    backgroundColor: 'rgba(4,217,196,0.16)',
  },
  reservaBadgeFull: {
    backgroundColor: 'rgba(255,107,107,0.16)',
  },
  reservaBadgeTextAvailable: {
    color: colors.accent1,
    fontWeight: '800',
    fontSize: 12,
  },
  reservaBadgeTextFull: {
    color: colors.danger,
    fontWeight: '800',
    fontSize: 12,
  },
  reservaStreetButton: {
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  reservaStreetButtonActive: {
    backgroundColor: colors.accent2,
  },
  reservaStreetButtonDisabled: {
    backgroundColor: colors.disabled,
  },
  reservaStreetButtonText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: 15,
  },
  reservaEmptyCard: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 18,
    padding: 22,
    alignItems: 'center',
  },
  reservaEmptyTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.primary,
    marginBottom: 6,
  },
  reservaEmptyText: {
    color: colors.textSecondary,
    textAlign: 'center',
  },
  reservaLoadingCard: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 18,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  reservaLoadingText: {
    color: colors.primary,
    fontWeight: '700',
  },
  reservaFormCard: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 20,
    padding: 18,
    marginTop: 22,
  },
  reservaFormTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.primary,
    marginBottom: 4,
  },
  reservaFormSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 10,
  },
  reservaSubmitDisabled: {
    backgroundColor: colors.disabled,
  },
  homeScreen: {
    flex: 1,
    width: '100%',
    backgroundColor: colors.background,
  },
  homeContent: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 20,
    paddingTop: 70,
  },
  homeGreeting: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.primary,
    marginBottom: 8,
  },
  homeSubtitle: {
    fontSize: 16,
    color: colors.accent2,
    marginBottom: 18,
  },
  homeMiniList: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 18,
    padding: 16,
    gap: 10,
  },
  homeMiniListItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(4,196,217,0.12)',
  },
  homeMiniListText: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  homeAdminHint: {
    marginTop: 18,
    color: colors.accent1,
    fontWeight: '700',
  },
  homeAdminGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  homeAdminCard: {
    width: '47%',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 18,
    padding: 18,
  },
  homeAdminCardWide: {
    width: '100%',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 18,
    padding: 18,
  },
  homeAdminLabel: {
    color: colors.accent1,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 10,
  },
  homeAdminValue: {
    color: colors.primary,
    fontSize: 30,
    fontWeight: '800',
  },
});
